github action

diff --git a/.github/workflows/pull-all.yml b/.github/workflows/pull-all.yml
--- a/.github/workflows/pull-all.yml
+++ b/.github/workflows/pull-all.yml
@@ -3,10 +3,45 @@ name: CI
 on:
   push:
     branches:
-      - debug
+      - prod
+      - dev
 
 jobs:
-  build:
+  build-prod:
+    if: github.ref == 'refs/heads/prod'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Run ssh commands
+        uses: appleboy/ssh-action@v0.1.10
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          password: ${{ secrets.SERVER_PASS }}
+          
+          port: 22
+          script: |
+            set -e
+            cd ~/academy-fe
+            git checkout prod
+            git pull
+            echo "yes"         
+            echo "VITE_API_URL=${{ secrets.VITE_API_URL_PROD }}"  >> .env.production
+            # Build the images first
+            if sudo docker-compose -f docker-compose-prod.yml build; then
+              # If build succeeds, stop old containers but keep the images
+              sudo docker-compose -f docker-compose-prod.yml down
+              # Start new containers
+              if sudo docker-compose up -d; then
+                echo "New version deployed successfully."
+                # Clean up old images
+                sudo docker image prune -af
+              fi
+            else
+              echo "Docker Compose build failed. Keeping current version running."
+            fi
+
+  build-dev:
+    if: github.ref == 'refs/heads/dev'
     runs-on: ubuntu-latest
     steps:
       - name: Run ssh commands
@@ -19,13 +54,14 @@ jobs:
           script: |
             set -e
             cd ~/academy-fe
-            git checkout debug
+            git checkout dev
             git pull
             echo "yes" 
+            echo "VITE_API_URL=${{ secrets.VITE_API_URL_DEV }}"  >> .env
             # Build the images first
-            if sudo docker-compose build; then
+            if sudo docker-compose -f docker-compose-dev.yml build; then
               # If build succeeds, stop old containers but keep the images
-              sudo docker-compose down
+              sudo docker-compose -f docker-compose-dev.yml down
               # Start new containers
               if sudo docker-compose up -d; then
                 echo "New version deployed successfully."
